language: groovy

jdk:
  - openjdk7

env:
- TERM=dumb

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
- chmod +x gradlew

script:
- ./gradlew clean build --full-stacktrace

after_success:
- ./gradlew jacocoTestReport coveralls --full-stacktrace
